### ISSUE TITLE
Upstream?

### ISSUE THREAD

**Issue by skorianez** [ddlsmurf/libfprint-CS9711#1]
Have you tried to upstream as patch to official libfprint?

**Comment by ericlinagora** [comment]
Somewhat: currently gitlab.freedesktop does not allow new users like me to fork to then create the MR, but it's still git so when the libfprint team grants permissions to me (or some of the other contributors in this issue), it should be easy. This also depends on another MR (sigfm), the main author of which has limited availability and because of the security implications, will need thorough testing before getting included, which is a pre-condition for this code base. You can track the status [in this issue](https://gitlab.freedesktop.org/libfprint/libfprint/-/issues/610).
